config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resources :trips, only: [:new, :edit, :create, :update, :show, :index, :destroy]
  resources :destinations, only: [:show, :index]
  resources :attractions, only: [:index, :show]
  resources :reviews, only: [:new, :edit, :create, :update, :show, :index, :destroy]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  belongs_to :destination
  has_many :reviews
  has_many :users, through: :reviews

  def total_reviews
    self.reviews.count
  end

  def ratings
    self.reviews.map {|review| review.rating.to_f }
  end

  def average_rating
    if self.ratings.length == 0
      "No reviews yet"
    elsif self.ratings.length > 0
      rating = self.ratings.sum/self.ratings.length
      "Average #{rating.round(1)}/5 Stars"
    end
  end

  def self.highest_rated_attraction
    top = self.all.first
    self.all.each do |attr|
      if attr.average_rating > top.average_rating
        top = attr
      end
    end
    top
  end

  def self.highest_rated_attraction_name
    self.highest_rated_attraction.name
  end

  def self.sort_alphabetically
    self.all.order(:name)
  end

end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :trips
  has_many :users, through: :trips
  has_many :attractions

  def self.sort_alphabetically
    self.all.order(:city)
  end

  def api_data
    url = URI("https://us-weather-by-city.p.rapidapi.com/getweather?city=#{self.city}&state=#{self.state}")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-host"] = 'us-weather-by-city.p.rapidapi.com'
    request["x-rapidapi-key"] = '7188ca30eemsh24dc91f4f4d2aeap15bbf4jsndeff3fcc5a96'
    response = http.request(request)
    JSON.parse(response.read_body)
  end

  def dest_temp
    self.api_data["TempF"]
  end

  def dest_weather
    self.api_data["Weather"]
  end

  def dest_humidity
    "#{self.api_data["RelativeHumidity"]}%"
  end
  
  def dest_air_quality
    self.api_data["AirQuality"]
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :attraction

  


end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :destination

  def reformat_date
    Date.parse(self.departure_date).strftime("%m/%d/%Y")
  end

  def self.all_destinations
    trip_dest = []
    self.all.each do |trip|
      trip_dest << trip.destination
    end
    trip_dest
  end

  def self.most_pop_dest_instance
    dests = self.all_destinations
    if dests.length == 0
      "No trips have been planned yet"
    elsif dests.length > 0
      freq = dests.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
      dests.max_by { |v| freq[v] }
    end
  end

  def self.most_pop_dest_city
    if self.all_destinations.length == 0
      nil
    else
    self.most_pop_dest_instance.city
    end
  end

  def self.order_by_recent
    self.all.order(:departure_date)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips
  has_many :destinations, through: :trips
  has_many :reviews
  has_many :attractions, through: :reviews

  validates_uniqueness_of :username, message: "has already been taken"

  validates :username, length: {minimum: 2, maximum: 15, message: "must be between 2-15 characters"}

  has_secure_password validations: false

  def all_trips
    Trip.all.select {|trip| trip.user_id == self.id}
  end

  def trip_count
    self.all_trips.count
  end

  def welcome_message
    if self.trip_count > 1
      "Currently, you have #{trip_count} trips planned"
    elsif self.trip_count == 0
      "You have no trips planned"
    elsif self.trip_count == 1
      "Currently, you have 1 trip planned"
    end
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  add_flash_types :danger, :info, :warning, :success

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController

  def index
    @attractions = Attraction.all
  end

  def show
    @attraction = Attraction.find(params[:id])
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  def index
    @destinations = Destination.all
  end

  def show
    @destination = Destination.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.save
    redirect_to review_path(@review)
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
  end

  def delete
    @review = Review.find(params[:id])
  end

  private
  def review_params
    params.require(:review).permit(:rating, :title, :comments, :attraction_id, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new

  end

  def login

  end

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome', success: "Successfully logged in"
    else
      redirect_to '/login', danger: "Invalid username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/welcome', success: "Successfully logged out"
  end

  def page_requires_login

  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.order_by_recent
  end

  def new
    @trip = Trip.new
  end

  def create

    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    @trip.departure_date = Date.new trip_params["departure_date(1i)"].to_i, trip_params["departure_date(2i)"].to_i, trip_params["departure_date(3i)"].to_i
    @trip.save
    redirect_to trip_path(@trip)
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path
  end

  def flights

  end

  private
  def trip_params
    params.require(:trip).permit(:user_id, :destination_id, :title, :description, :departure_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id #changes session user_id to new user's user_id
      redirect_to '/welcome'
    else
      render :new
    end

  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :location, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.erb
 
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= name %>'>
    <%= msg %>
    </div>
    <%end%>

app/views/attractions/index.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>

<div class="row" style="padding-top:4%;">
<div class="col"></div>
<div class="col-md-8 text-center">

<h1 class="text-white font-italic"><strong>Attractions</strong></h1><br>

<h3 class="text-white">Top Rated Attraction</h3><br>
<div class="card mb-3">
<img src="<%= Attraction.highest_rated_attraction.image%>" class ="card-img-top" style:"width:50%; height:30%", alt="most_popular_attraction_image">
<div class="card-body">
<h5 class="card-title"><%= link_to Attraction.highest_rated_attraction_name, attraction_path(Attraction.highest_rated_attraction), {:style=>'color:black; font-size:25px;', :class => "css_class"} %></h4>
</div>
</div>
<br><br>

<table class="table table-hover" style="width:70%; margin-left:100px">
<thead>
  <tr>
  <tr scope="col"><h3 class="text-white">All Attractions</h3></tr>
  </tr>
</thead>
<% @attractions.sort_alphabetically.each do |attr|%>
  <tbody>
  <tr>
  <td scope="row"><%= link_to attr.name, attraction_path(attr), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %></td>
  </tr>
  <%end%>
</tbody>
</table>
<br>

</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/attractions/show.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>


<div class="row" style="padding-top:5%;">
<div class="col"></div>
<div class="col-md-7 text-center">

<h1 class="text-white font-italic"><strong><%= @attraction.name %></strong></h1>
<p class="text-white font-italic"><%= @attraction.description %></p><br>

<img src="<%= @attraction.image %>" alt="attraction picture" width="600" height="300">
<br><br><br>

<h3 class="text-white">Reviews</h3>

<h4 class="text-white"><%= @attraction.average_rating %></h4>
<br><br>

<table class="table table-hover" style=";">
<thead>
<tr>
<tr scope="col"><h5 class="text-white" style=";">Title of the Review & Rating</h5>
</tr>
</thead>
<% @attraction.reviews.each do |review|%>
  <tbody>
  <tr>
  <td scope="row" class="text-white"><%= link_to review.title, review_path(review), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"}%> - Rating: <%= review.rating %>/5</td>
  </tr>
<%end%>
</tbody>
</table>
<br>
<br>
<div class="btn-group" role="group" aria-label="Basic example">
<%= button_to "Create Review", '/reviews/new', class:"btn btn-md btn-secondary", method: :get%></button>
<%= button_to "City Page", destination_path(@attraction.destination_id), class:"btn btn-md btn-secondary", method: :get %></button>
</div><br><br><br><br>

</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/destinations/index.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>



<div class="row" style="padding-top:4%;">
<div class="col"></div>
<div class="col-md-8 text-center" style="margin-right:200px;">

<h1 class="text-white font-italic"><strong>Destinations</strong></h1>
<br>
<h3 class="text-white">Most Popular Destination</h3><br>
<div class="card mb-3">
<img src="<%= Trip.most_pop_dest_instance.image%>" class="card-img-top" style:"width:50%; height:30%", alt="most_popular_dest_image">
<div class="card-body">
<h5 class="card-title"><%= link_to Trip.most_pop_dest_city, destination_path(Trip.most_pop_dest_instance), {:style=>'color:black; font-size:25px;', :class => "css_class"} %></h5>
</div>
</div>

<br><br>

    <div class="col-5 col-center">
<table class="table table-hover" style="margin-left:200px;">
<thead>

  <tr>
  <tr scope="col col-center"><h3 class="text-white" style="margin-left:300px;">Cities</h3>
  </tr>
 </thead>
<% @destinations.sort_alphabetically.each do |dest|%>
  <tbody>
  <tr>
  <td scope="row"><%= link_to dest.city, destination_path(dest),{:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %></td>
  </tr>
<%end%>
</tbody>
</table>
</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/destinations/show.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>


<div class="row" style="padding-top:4%;">
<div class="col"></div>
<div class="col-md-7 text-center">


<h1 class="text-white font-italic"><strong><%= @destination.city %></strong></h1><br>
<img src="<%= @destination.image %>" alt="city picture" width="600" height="300"><br><br>

<h3 class="text-white">Current Weather</h3>
<p class="text-white" style="list-style-type:none;">
  <p class="text-white"><%= @destination.dest_weather %></p>
  <p class="text-white"><%= @destination.dest_temp %> &#176 F</p>
  <p class="text-white"><%= @destination.dest_humidity %> Humidity</p>
  <p class="text-white">Air Quality: <%= @destination.dest_air_quality %></p>
</p>

<br><br>

<table class="table table-hover" style="width:70%; margin-left:90px;">
<thead>
  <tr>
  <tr scope="col"><h4 class="text-white">Attractions</h5>
  </tr>
<% @destination.attractions.each do |attr|%>
<tbody>
  <tr>
  <td scope="row"><%= link_to attr.name, attraction_path(attr), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %></td>
  </tr>
<%end%>
</tbody>
</table>
<br>

<%= button_to "Back to Destinations", '/destinations', class:'btn btn-md btn-secondary', method: :get%>
<br>
</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Example</h1>
<p>Lorem ipsum …</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JTAirline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'flash_messages' %>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/index.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>


<div class="row" style="padding-top:10%;">
<div class="col"></div>
<div class="col-md-7 text-center">

<h1 class="text-white font-italic"><strong>Reviews</strong></h1><br><br>

<table class="table table-hover" style="width:70%; margin-left:90px;">
<thead>
  <tr>
  <tr scope="col"><h5 class="text-white">All Attraction Reviews</h5>
  </tr>
</thead>
<% @reviews.each do |review|%>
  <tbody>
  <tr>
  <td scope="row" class="text-white"><%= link_to review.attraction.name, attraction_path(review.attraction), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %> - "<%= link_to review.title, review_path(review), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %>"</td>
  </tr>
<%end%>
</tbody>
</table>

<br><br><%= button_to "New Review", new_review_path, class:'btn btn-md btn-secondary', method: :get %>

</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/reviews/show.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>


<div class="row" style="padding-top:4%;">
<div class="col"></div>
<div class="col-md-7 text-center">

<h2 class="text-white"><u><%= @review.attraction.name %></u></h2>
<br>
<h4 class="text-white">"<%= @review.title %>"</h4><br>
<br>
<h4 class="text-white">Rating: <%= @review.rating %>/5 Stars</h4>
<br>
<p class="text-white"><%= @review.comments %></p>
<p  class="text-white">User: <%= @review.user.first_name%> <%= @review.user.last_name%></p>
<br>
<br>

<% if @review.user == current_user %>
<%= button_to "Edit", edit_review_path(@review.id), class:"btn btn-md btn-secondary", method: :get%>
<% end %>
<br>
</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->

app/views/trips/flights.html.erb
flights!

app/views/trips/index.html.erb
<div class="background">
<div class="row" style="padding-top:1%; padding-bottom:2%;">
<%= image_tag 'photo/logo4.png', style:"width:25%; height:10%" %><br><br>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/welcome">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%if logged_in?%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/trips">My Trips</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/destinations">Destinations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/attractions">Attractions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reviews">Reviews</a>
        </li>
    </ul>
    <span class="nav-item">
      <%= link_to "Logout", '/logout', method: :delete %>
    </span>
    <%else%>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
      </ul>
    <%end%>
</nav>


<div class="row" style="padding-top:4%;">
<div class="col"></div>
<div class="text-center">

<h1 class="text-white font-italic"><strong>My Trips</strong></h1><br><br>
<div class='grid-center'>
<table class="table table-hover" style="width:100%">
<thead>
  <tr>
    <tr scope="col"><h5 class="text-white">Trip Names</h5>
  </tr>
</thead>
<% @trips.each do |trip|%>
<tbody>
  <tr>
    <td scope="row"><%=link_to trip.title, trip_path(trip), {:style=>'color:lightgray; font-size:18px;', :class => "css_class"} %></td>
  </tr>
<%end%>
</tbody>
</table>
<br>
</div>
<br>
<%= button_to "New Trip", new_trip_path, class:'btn btn-md btn-secondary', method: :get %>
<br>


</div><!-- .col-md-7 -->
<div class="col"></div>
</div><!-- .row -->